export interface OllamaModelTag {
    name: string;
    model: string;
    modified_at: string;
    size: number;
    digest: string;
    details: {
        format: string;
        family: string;
        families: string[];
        parameter_size: string;
        quantization_level: string;
    };
}

export interface OllamaShowResponse {
    modelfile: string;
    parameters: string;
    template: string;
    details: Record<string, unknown>;
}

export class FixtureFactory {
    public static createModelTag(name: string, overrides: Partial<OllamaModelTag> = {}): OllamaModelTag {
        return {
            name,
            model: name,
            modified_at: new Date().toISOString(),
            size: 1000000,
            digest: 'mockdigest',
            details: {
                format: 'gguf',
                family: 'llama',
                families: ['llama'],
                parameter_size: '7b',
                quantization_level: 'Q4_0'
            },
            ...overrides
        };
    }

    public static createShowResponse(name: string, overrides: Partial<OllamaShowResponse> = {}): OllamaShowResponse {
        const template = '{{ .System }}{{ .Prompt }}';
        const parameters = 'stop\t"[INST]"\nstop\t"[/INST]"';
        return {
            modelfile: `# Modelfile generated by "ollama show"\nFROM ${name}\nTEMPLATE """${template}"""\nPARAMETER stop "[INST]"\nPARAMETER stop "[/INST]"\n`,
            parameters,
            template,
            details: {},
            ...overrides
        };
    }

    public static createChatChunk(model: string, content: string, done: boolean = false) {
        return {
            model,
            created_at: new Date().toISOString(),
            message: {
                role: 'assistant',
                content
            },
            done
        };
    }

    public static createGenerateChunk(model: string, response: string, done: boolean = false) {
        return {
            model,
            created_at: new Date().toISOString(),
            response,
            done
        };
    }
}
